[workspace]
members = ["cli", "server"]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1.47.0", features = ["macros", "rt-multi-thread", "fs"] }
tokio-util = { version = "0.7.15", features = ["io"]}
serde = { version = "1.0", features = ["derive"] }
rand = "0.9.2"
